<?php

/**
 * Implementation file for Data Fusion Module. 
 * Module handles output of news webscraping algorithm which finds outside sources relevant to user created content.
 * Implements and overrides various default drupal hook functions for display customization.
 * In order to add in authentication and authorization restrictions for editing, implement hook_perm() and use 'global $user;' to check user
 * Drupal Custom Module for Sun_In_The_City, Cornell Daily Tech Newspaper
 * Author: Sean Salmon
 */
 

/**
 * Implements hook_help().
 */
function datafusion_help($section = 'admin/help#datafusion', $arg = NULL) {
  $output = '';
  
  // Only one help section for now
  switch ($section) {
    case 'admin/config/content/datafusion':
      $output = t('Data Fusion allows editors to have articles from around the internet included in their articles. Module performs web scraping algorithm and user input data to populate additional sources of content.');
       $output .= '<h3> ' . t('Warning: Deleting Data Sources also deletes ALL Data Fusion and Data Means elements associated with it.'.' </h3>');
      
      $output = '<p>' . $output . '</p>';
      break;
   	case 'admin/help#datafusion':
      $output = t("<p>This module lets you add in aggregated data from relevant internet news sources to your articles.</p>
      <p>To start using Data Fusion, there are two interfaces</p>
	  
	  <strong><h3>For Writers:</h3></strong>
      <ul>
        <li>After you have created an Article, you will notice a tab on the top labeled 'Data Fusion' which will allow you to begin working with Data Fusion. </li>
        <li>You will immediately notice a list of aggregated news data at your disposal to choose from. If you would like an outside source to appear alongside your article, simply select the corresponding check box and press the 'Approve' button. </li>
        <li>Conversely, if you would lke to remove an outside source, simply select the source and click 'Delete'.</li>
 <li>You also have the option of adding in your own outside news data that you find relevant using the form displayed underneath. To proceed fill in the textfields, select a rating for the article (The higher ranked articles receive priority in the order in which articles are displayed) and select the source from which the data was obtained. </li>
 		<li> To edit any particular entry, select its respective checkbox and press the 'Edit' button. Once clicked the edit button will show the fields to be updated below the table. </li> 
        <li>Your data fusion articles are now ready to be shown!</li>
      </ul>  
	  <strong><h3>For Editors:</h3></strong>
      <ul>
        <li>For the editor's interface within the admin/modules configuration page, you have the choice of configuring data fusion articles, data source and data means. </li>
        <li>The Data Fusion table shows the complete list of data fusion articles connected to every article on the website.  </li>
        <li>To Configure simply select an entry and click either 'Approve', 'Edit' or 'Delete'.  </li>
 		<li>Underneath Data Fusion area is a collapsable field representing all of the Data Sources on the website. Just as previously before, you can edit or delete sources using the same convention. </li>
 		<li> To add Data Sources, complete the textfields and press the add button displayed underneath. <strong>Make sure the url to the logo image is valid, otherwise there will be no image displayed!</strong> also, <strong> be sure to remember that deleting data sources deletes any connected means as well. </strong> </li> 
        <li>Data Means are simply the secondary mean by which an article obtains its sources such as an RSS or Twitter Feed. Feel free to configure the means to your desire using the conventions restated multiple times within this help notice. </li>
      </ul>
	  
      ");
      break;
  }

  return $output;
}

/**
 * Implements hook_menu().
 */
function datafusion_menu() {
  $items = array();

  // Admin Configuration Settings.
  $items['admin/config/content/datafusion'] = array(
    'title' => 'Data Fusion Settings',
    'page callback' => 'admin_config_page',
    'access callback' => 'user_access',
    'access arguments' => array('administer site configuration'),
    'file' => 'includes/datafusion.admin.inc',
    'type' => MENU_LOCAL_TASK,
  );
  
	
  // Initialize View in Admin > Configuration Menu
  $items['admin/config/datafusion'] = array(
    'title' => 'Data Fusion',
	'position' => 'left',
	'weight' => -100,
	'page callback' => 'system_admin_menu_block_page',
	'access arguments' => array('administer site configuration'),
	'file' => 'system.admin.inc',
	'file path' => drupal_get_path('datafusion', 'system'),
  );
  
  // Actual View in Admin>Configuration>DataFusion
  $items['admin/config/datafusion/configuration'] = array(
	'title' => 'Data Fusion Settings',
	'description' => 'View and edit all the available Data Fusion Articles on your site.',   
	'page callback' => 'admin_config_page',
	'access arguments' => array('administer site configuration'),
 	'file' => 'includes/datafusion.admin.inc',
  );

	//Data Fusion Node Tab - displayed at the top of every article 
  $items['node/%node/datafusion'] = array(
    'title' => 'Data Fusion',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('datafusion_configure_form', 1),
    'access callback' => 'node_access',
    'access arguments' => array('update', 1),
    'file' => 'includes/datafusion.node.inc',
    'weight' => 3,
    'type' => MENU_LOCAL_TASK,
    'context' => MENU_CONTEXT_PAGE | MENU_CONTEXT_INLINE,
  );
  
  return $items;
}

/**
 * Implements hook_admin_paths().
 */
function datafusion_admin_paths(){
	$paths['node/*/datafusion'] = TRUE;
	return $paths;
}
 

/** 
 * Implements hook_admin_paths_alter().
 */
function datafusion_admin_paths_alter(&$paths){
	$paths['node/*/datafusion'] = TRUE; // Allow Datafusion tab to be shown is drupal overlay 
}


//Uncomment this function to create restrictions on certain parts of the Data Fusion Module and manage authorization for privacy concerns.
/**
 * Implements hook_perm().
 */
/**
function datafusion_permission() {
  return array(
    'access all Data Fusion articles' => array(
      'title' => t('Access all Data Fusion Articles'),
      'description' => t('Grants access to the "Data Fusion" tab on all articles. Generally an administrative permission.'),
    ),
    'access own Data Fusion articles' => array(
      'title' => t('Access own Data Fusion Articles'),
      'description' => t('Grants access to the "Data Fusion" tab to the author of article they have created.'),
    ),
    'edit all Data Fusion articles' => array(
      'title' => t('Edit all webform submissions'),
      'description' => t('Allows editing of any Data Fusion article to author of article they have created. Generally an administrative permission.'),
    ),
    'delete all Data Fusion articles' => array(
      'title' => t('Delete all webform submissions'),
      'description' => t('Allows deleting of any Data Fusion by any user. Generally an administrative permission.'),
    ),
    'access Data Sources' => array(
      'title' => t('Access to Admin Data Source Configuration'),
    ),
    'edit Data Sources' => array(
      'title' => t('Edit Admin Data Source Configuration'),
    ), 
    'delete Data Sources' => array(
      'title' => t('Delete Admin Data Source Configuration'),
    ),
	'access Data Meanss' => array(
      'title' => t('Access to Admin Data Means Configuration'),
    ),
    'edit Data Means' => array(
      'title' => t('Edit Admin Data Means Configuration'),
    ), 
    'delete Data Means' => array(
      'title' => t('Delete Admin Data Means Configuration'),
    ),
  );
}
*/